#!/bin/bash

#C# $(app_list)
#C--# --force

tb_getopt app - $@

d_app=$d_apps/$app

[ "$force" = "on" ] || ask_N_stop "are you sure you want remove '$app'"

tb mysql sudo/grant revoke $app --force
tb mysql sudo/user/remove $app --force
tb mysql sudo/db/remove	$app --force

f_nginx=/etc/nginx/sites-enabled/10-$app.conf


rm -rf $f_nginx

app_teardown_fpm_and_processes $app

service nginx reload || true

if getent passwd $app &> /dev/null
then
	userdel $app -r
fi

rm -rf $d_app


