#!/bin/bash

#C# $(app_list)
#C--# --force

tb_getopt app - $@

d_app=$d_apps/$app

[ "$force" = "on" ] || ask_N_stop "are you sure you want remove '$app'"

tb mysql sudo/grant revoke $app --force
tb mysql sudo/user/remove $app --force
tb mysql sudo/db/remove	$app --force

f_nginx=/etc/nginx/sites-enabled/10-$app.conf

rm -rf $f_nginx

f_apache2_80=/etc/apache2/sites-enabled/10-$app.conf
f_apache2_443=/etc/apache2/sites-enabled/10-$app-le-ssl.conf

rm -rf $f_apache2_80
rm -rf $f_apache2_443

app_teardown_fpm_and_processes $app

service nginx reload || true

service apache2 restart || true


if getent passwd $app &> /dev/null
then
	userdel $app -r
fi

rm -rf $d_app


