#!/bin/bash
export DEBIAN_FRONTEND=noninteractive

tb_getopt timezone=Europe/Paris locale=en_US.UTF-8 - $@

PACKAGES="curl wget ncdu iftop iotop tree unzip htop gnupg ca-certificates lsb-release debian-archive-keyring net-tools readline-common pv git"
# software-properties-common: Ubuntu uniquement, absent sur Debian 13+
apt-cache show software-properties-common >/dev/null 2>&1 && PACKAGES="$PACKAGES software-properties-common"

apt install -y $PACKAGES

timedatectl set-timezone $timezone

sed -i "/$locale UTF-8/d" /etc/locale.gen
echo $locale UTF-8 >>/etc/locale.gen
update-locale LANG=$locale LANGUAGE=$locale LC_ALL=$locale

dpkg-reconfigure --frontend=noninteractive locales

date
