#!/bin/bash

# Utiliser mariadb si disponible, sinon mysql (compatibilité vieux systèmes)
if command -v mariadb >/dev/null 2>&1; then
  MYSQL_CMD=mariadb
else
  MYSQL_CMD=mysql
fi

# Exécuter mysql/mariadb en filtrant uniquement le warning de dépréciation
function mysql_exec() {
  # Créer un fichier temporaire pour stderr
  local stderr_file=$(mktemp)
  
  # Exécuter la commande en capturant stderr séparément
  "$@" 2>"$stderr_file"
  local exit_code=$?
  
  # Filtrer et afficher stderr en excluant le warning de dépréciation
  if [ -s "$stderr_file" ]; then
    grep -v "mysql: Deprecated program name" "$stderr_file" >&2
  fi
  
  # Nettoyer
  rm -f "$stderr_file"
  
  return $exit_code
}

function mysql_query {
	local db_user db_passwd file d_home db_host_to db_port the_port

	# 	[ -z "$SQL" ] && return 0

	[[ "$@" =~ ^.*-h\ ?([a-z0-9.]*).* ]] && db_host_to=${BASH_REMATCH[1]}

	[ -z "$db_host_to" ] && db_host_to=localhost

	db_user=$(id -u -n)

	d_home=$(grep ^$db_user: /etc/passwd | awk -F[:] '{print $6}')

	f_port=$d_home/etc/mysql/$db_host_to/port
	if [ -e $f_port ]; then
		db_port=$(cat $f_port)
	fi

	if [[ $db_host_to != "localhost" && -z "$db_port" ]]; then
		db_port=4231
	fi

	[ -n "$db_port" ] && the_port="-P $db_port"

	f_cnf=$d_home/.my.cnf

	if [ -e $f_cnf ]; then
		if [ -n "$SQL" ]; then
			echo "$SQL" | mysql_exec $MYSQL_CMD -B -u$db_user -h$db_host_to -s $the_port $@
		else
			mysql_exec $MYSQL_CMD -B -u$db_user -h$db_host_to -s $the_port $@ <&0
		fi
	else
		echoc -y1 "$f_passwd unexistant !"
	fi

	return 0
}

function mysql_user_list {
	local SQL
	SQL="SELECT CONCAT(user,'@',host) FROM user;"

	if [ -n "$db_host_to" ]; then
		the_host="-h $db_host_to"
	fi

	mysql_query mysql $the_host | sed -e '/^root@localhost$\|^debian-sys-maint@localhost$/d'

	return 0
}

function mysql_db_list {
	local SQL

	SQL="SHOW DATABASES;"

	if [ -n "$db_host_to" ]; then
		the_host="-h $db_host_to"
	fi

	mysql_query mysql $the_host | sed -e '/^mysql$\|^information_schema$\|^performance_schema$\|^sys$\|lost+found/d'

	return 0
}

function mysql_table_list {
	local SQL

	SQL="SELECT TABLE_NAME FROM TABLES WHERE TABLE_SCHEMA='$1';"

	if [ -n "$db_host_to" ]; then
		the_host="-h $db_host_to"
	fi

	mysql_query information_schema $the_host

	return 0
}

return 0
