#!/bin/bash

#C# All $(app_list) $(tb mysql sudo/db/list)
#C# All db app
tb_getopt app=All type=All - $@

date=$(date +'%y-%m-%d-%HH%M')
d_sav1=/var/sav1/$(hostname)
mkdir -p $d_sav1/{auto,system}

backs_auto=7
backs_sytem=7

[ -e /etc/tb/backup ] && . /etc/tb/backup

# Convention: le dossier nosav est toujours exclu des backups
nosav="--exclude=./nosav"

if [ "$app" = All ]; then
	for i in $(find $d_sav1/auto -maxdepth 1 -mindepth 1 -type d | sort | tac | sed $backs_auto',$!d'); do
		rm -rf $i
	done

	for i in $(find $d_sav1/system -maxdepth 1 -mindepth 1 -type d | sort | tac | sed $backs_sytem',$!d'); do
		rm -rf $i
	done

	date
	echo "############## SYSTEM ############## "

	dir=$d_sav1/system/$date
	mkdir -p $dir

	# Backup /etc
	echo "############## $dir/etc ##############"
	tar cjf $dir/etc.tar.bz2 -C /etc . | true

	# Backup /root : seulement les fichiers essentiels qui existent
	echo "############## $dir/root ##############"
	root_files=""
	for f in .ssh .bash_history .bashrc .bash_profile .profile .my.cnf .vimrc .gitconfig sav; do
		[ -e /root/$f ] && root_files="$root_files $f"
	done
	[ -n "$root_files" ] && tar cjf $dir/root.tar.bz2 -C /root $root_files | true
	echo

	date
	echo "############## ALL MYSQL ##############"
	for i in $(tb mysql sudo/db/list); do
		[ $i == performance_schema ] && continue
		[ $i == information_schema ] && continue

		dir=$d_sav1/auto/$date/$i
		echo "############## $dir"
		mkdir -p $dir

		tb mysql sudo/db/dump --triggers --routines $i | bzip2 >$dir/$i.sql.bz2
	done
	echo

	date
	echo "############## ALL APPs ##############"
	for app in $(app_list); do
		dir=$d_sav1/auto/$date/$app

		echo "############## $dir"

		mkdir -p $dir
		tar cjf $dir/$app.tar.bz2 $nosav -C /apps/$app .

		[ -e /var/spool/cron/crontabs/$app ] && cp -vf /var/spool/cron/crontabs/$app $dir/crontab

	done

	date
	for i in $(app_list) $(tb mysql sudo/db/list); do
		du -sh $d_sav1/auto/$date/$i
	done
	date
	echo
else
	dir=$d_sav1/manual/$app/$date
	mkdir -p $dir

	if [[ "$type" = "All" || "$type" = "app" ]]; then
		echo "############## MANUAL $app APP $dir/$app.tar.bz2"
		tar cjf $dir/$app.tar.bz2 $nosav -C /apps/$app .
		[ -e /var/spool/cron/crontabs/$app ] && cp -vf /var/spool/cron/crontabs/$app $dir/crontab
	fi

	if [[ "$type" = "All" || "$type" = "db" ]]; then
		echo "############## MANUAL $app DB $dir/$app.sql.bz2"
		tb mysql sudo/db/dump --triggers --routines $app | bzip2 >$dir/$app.sql.bz2
	fi

	echo
	echo "############## Done"
fi
