#!/bin/bash

# Utiliser mariadb si disponible, sinon mysql
if command -v mariadb >/dev/null 2>&1; then
  MYSQL_CMD=mariadb
else
  MYSQL_CMD=mysql
fi

tb_getopt app - $@

template=joomla

. $TB_MODULE_DIR/confs/base

[ ! -e $d_stock ] && tb template sudo/$template/download

rm -rf $d_app/app

mkdir -p $d_app/app

cp -r -v $d_stock $d_app/app/webroot

tb app sudo/bulldozer $app


d_config=$TB_MODULE_DIR/templates/joomla



cp -v $d_config/configuration.php $d_app/app/webroot

cat $d_config/joom.sql | $MYSQL_CMD $app

